name: Android CI

on:
  pull_request:
    branches: [ 'develop' ]
  push:
    branches: [ 'master' ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
      - uses: kkak10/pr-number-action@v1.3
        id: bh-pr-number

      - name: telegram-message-start
        uses: appleboy/telegram-action@v0.1.1
        with:
          token: 5218142328:AAF8xJCg7DR2dQqRkGXq-exYugcJCBI4cw8
          to: -600920147
          message: |
            ⚠️⚠️⚠️⚠️⚠️

            Build Dropp STARTED. Run: #${{ github.run_number }}.

            Commit by @${{ github.actor }}

            Links:
            Pull request: https://github.com/${{ github.repository }}/pull/${{ steps.bh-pr-number.outputs.pr }}
            Changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}

      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'

      - name: cache-gradle-packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: build
        run: |
          ./gradlew build

      - name: telegram-message-failed
        if: ${{ failure() }}
        uses: appleboy/telegram-action@v0.1.1
        with:
          token: 5218142328:AAF8xJCg7DR2dQqRkGXq-exYugcJCBI4cw8
          to: -600920147
          message: |
            ❌❌❌❌❌

            Build Dropp Handbook FAILED. Run: #${{ github.run_number }}.

            Commit by @${{ github.actor }}

            Links:
            Pull request: https://github.com/${{ github.repository }}/pull/${{ steps.bh-pr-number.outputs.pr }}

      - name: generate-artifacts
        run: |
          ./gradlew bundleRelease

#      - name: upload-debug-apk
#        uses: actions/upload-artifact@v2.2.1
#        with:
#          name: Debug Apk
#          path: app/build/outputs/apk/debug
#
#      - name: upload-release-apk
#        uses: actions/upload-artifact@v2.2.1
#        with:
#          name: Release Apk
#          path: app/build/outputs/apk/release
#
#      - name: upload-release-aab
#        uses: actions/upload-artifact@v2.2.1
#        with:
#          name: Release Aab
#          path: app/build/outputs/bundle/release

      - name: telegram-message-success
        uses: appleboy/telegram-action@v0.1.1
        with:
          token: 5218142328:AAF8xJCg7DR2dQqRkGXq-exYugcJCBI4cw8
          to: -600920147
          message: |
            ✅✅✅✅✅

            Build Dropp Handbook SUCCESS. Run: #${{ github.run_number }}.

            Links:
            Pull request: https://github.com/${{ github.repository }}/pull/${{ steps.bh-pr-number.outputs.pr }}
            Artifacts: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}